/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/get-order-book": {
    get: operations["AppController_getOrderBook"];
  };
}

export interface components {
  schemas: {
    OrderBookBidDTO: {
      price: number;
      size: number;
    };
    OrderBookAskDTO: {
      price: number;
      size: number;
    };
    OrderBookDTO: {
      bids: components["schemas"]["OrderBookBidDTO"][];
      asks: components["schemas"]["OrderBookAskDTO"][];
    };
  };
}

export interface operations {
  AppController_getOrderBook: {
    parameters: {};
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["OrderBookDTO"];
        };
      };
    };
  };
}

export interface external {}
